services:
  redis:
    image: redis:3.2
  web:
    build:
      context: /home/shiyanlou/app/web
# 定义依赖关系 被依赖容器需要先创建
    depends_on:
    - redis
    ports:
    - 8001:80/tcp
    volumes:
    - /home/shiyanlou/app/web:/web:rw
version: '3.0'
